# (PART) HTML {-}

# HTML 简介 {#html-histroy}

HTML（HyperText Markup Language，超文本标记语言）是为“网页创建和其它可在网页浏览器中看到的信息”设计的一种标记语言。

## HTML 发展简史

互联网最底层是计算机，没有计算机就没有互联网，1941 年德国人祖斯发布可编程的计算机，1976 年苹果发布面向个人用户的微型计算机，计算机保有量达到一定规模后，计算机之间如何沟通就成为问题，网络脱胎于麻省理工学院的一个教授乔治·威利，在 1956 年，当时为了防止美国遭受核爆炸，建立了雷达检测网，有了计算机网络的雏形，然后到 1973 年的以太网，发明者是麦特卡尔夫。计算机网络发展到一定阶段，不同的计算机网络之间的互联互通又成为重要课题，互联网应用而生，1969 年的阿帕网到 1975 年瑟夫和卡恩发明的 TCP/IP。互联网在发展过程中出现资料访问繁琐、学习成本高昂的问题，万维网和浏览器就是上述问题的解决方案。从布什、纳尔逊、恩格尔巴特来到 1990 年的伯纳斯-李，然后有了所谓的 HTTP 和之后的 Mosaic 浏览器。互联网万维站点的爆发，使得信息过剩，如何准确快速地获取信息又成为主要问题，搜索引擎开始崭露头角，搜索引擎最早是 1990 年的 Archie，到 1998 年谷歌的出现。最后才来到今天大家所见到的丰富多彩的内容，这个内容是建立在万维网基础上的。

互联网的诞生早于万维网 15 年，但起初因使用技术复杂难以普及，互联网的用户局限在大学、军事、科研机构等有限的群体。万维网的发明是公认的促使互联网迅速发展的重要因素。万维网借助与 HTML 文档，使用超文本链接，把不同电脑上的文本、图像、声音等文档链接在一起，使人们不必受电脑操作系统类别和地域等限制，就可以自由浏览和分享信息，互联网的操作因而大大简化。

HTML 是万维网的基础，通过结合其他 Web 技术，可以创造出功能强大的网站，我们通过浏览器看到的信息就是用 HTML 呈现出来的。

HTML 最初是由万维网之父——蒂姆·伯纳斯-李给出了原始定义。1991 年，蒂姆·伯纳斯-李在互联网上公布了名为“HTML tag”的文档，详细说明了 HTML 组织信息的方式。之后，其它互联网组织和公司不断丰富 HTML 的功能，使之能够以直观的方式显示互联网中的文字、图片等信息，并通过超链接进行访问。随着互联网的爆炸式发展，商业利益的争夺也体现在 HTML 规则的制定中，以微软为代表的企业开始在浏览器中加入私有标签，这在相当程度上造成了 HTML 规则的混乱。

为了防止 HTML 受到商业利益的侵蚀，蒂姆·伯纳斯-李发起成立了万维网联盟（World Wide Web Consortium，W3C）, 接管了 HTML 的维护工作，并于 1997 年发布了 HTML3.2 版本和 4.0 版本。1999 年，万维网联盟推出了 HTML4.01 版本，加入了表格、表单和对象等特征。HTML4.01 版本是一个广泛采用的版本。

HTML4.01 发布之后，蒂姆·伯纳斯-李认为互联网的未来应该更加智能化，语义化，所以调整 HTML 的发展方向，停止了对 HTML 的升级，在 2000 年推出了 XHTML1.0，XHTML 是在 HTML4.01 基础上的优化和改进，XHTML 和 HTML4.01 之间只有极小但重要的区别。但是广大的互联网用户对于 HTML 的热情和需求不减反增，蒂姆·伯纳斯-李和万维网联盟最终推翻了之前的想法，认为 HTML 还是有很大的发展潜力，并于 2008 年推出了 HTML5 的草案，将工作重心重新调整到 HTML 的完善上。

2014 年 10 月 28 日，HTML5 正式发布，国内外一些互联网巨头已经将其应用到各自的网站中，比如 Google、Youtube、百度和淘宝等等。

2017 年 12 月 14 日，HTML5.2 发布。变化内容如下<https://www.w3.org/TR/html52/changes.html#changes>。

## 在线学习资源及工具

1. [HTML5 全景资料](https://developer.mozilla.org/zh-CN/docs/Web/Guide/HTML/HTML5)
1. [慕课网 HTML+CSS 基础课程](http://www.imooc.com/learn/9)
1. [Learn to Code HTML & CSS](http://learn.shayhowe.com/html-css/)
1. [强大的在线编辑、学习、发布平台](https://thimble.mozilla.org/zh-CN/)
1. [W3C HTML5 官方文档](https://www.w3.org/TR/html5/)
1. [HTML 语法验证工具](http://validator.w3.org/)
1. [HTML 知识在线测验](https://www.nowcoder.com/intelligentTest)

## 扩展阅读资料

1. <https://www.w3.org/TR/2017/REC-html52-20171214/introduction.html#introduction-history>
